#应用名称
spring:
  application:
    name: flow-limit-spring-boot-starter
  redis:
    host: 192.168.16.87
    port: 6379
    #    password: zkredis
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8

flowlimit:
  enabled: true
  redis-flow-limit-aspect-properties:
    enabled-global-limit: false
    enabled-sync-count: false
    prefix-key: "icecream::innovative-medicine:desktop-web:redis:flow:limit"
    counter-keys:
      - "counter:1:second:"
      - "counter:2:minutes:"
      - "counter:5:minutes:"
      - "counter:1:hour11:"
    counter-holding-time:
      - 1000
      - 180000
      - 300000
      - 3600000
    counter-limit-number:
      - 5
      - 80
      - 320
      - 240000

