#应用名称
spring:
  application:
    name: flow-limit-spring-boot-starter
  redis:
    host: 192.168.16.87
    port: 6379
    #    password: zkredis
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8

flowlimit:
  enabled: true
  redis-flow-limit-aspect-properties:
    enabled-global-limit: true
    prefix-key: "icecreamtest::innovative-medicine:desktop-web:redis:flow:limit"
    counter-keys:
      - "counter:second:3:"
      - "counter:minutes:2:"
      - "counter:minutes:5:"
      - "counter:hour:1:"
    counter-holding-time:
      - 3
      - 180
      - 300
      - 3600
    counter-limit-number:
      - 5
      - 80
      - 320
      - 240000

